### ISSUE TITLE
C# - Recursively browse the BlueSound Menu System with DataGridView

### ISSUE THREAD

**Issue by billhunter31** [roblans/Blu4Net#12]
Hi Rob,

I wanted to thank you for developing the Blu4Net library. It's been really useful for me and I appreciate your expertise in C#.

I've been trying to create an application that can browse the BlueSound Node menu system, starting at the top of the menu and navigating down to playing a radio station (similar to BlueSound's iOS application). I've been using the BluDumper example as a guide, but I'm having trouble implementing this in a Winform application using a DataGridView control. Do you have any suggestions for how I might be able to accomplish this?

Thanks,
Bill Hunter

**Comment by billhunter31** [comment]
Good-Morning Rob -  I wanted to let you know that I figured out how to recursively browse the BlueSound Node menu system using Winform’s DataBrowseGrid control.  Initially I was overwhelmed by the “challenge” of the coding task, (I’m a retired real estate person with little schooling/experience in coding in c#) but eventually figured it out and got it to work.  If anyone has any interest in seeing/using the code that I cobbled together, please feel free to leave me a message and I’d be more than happy to share what I’ve completed.  
Thanks again Rob - I truly love the Blu4Net library and admire your work.  
Bill Hunter

**Comment by roblans** [comment]
Great that you got it working! 

Rob.
