### ISSUE TITLE
long polling - how it works?

### ISSUE THREAD

**Issue by andyrichter** [roblans/Blu4Net#2]
Hello Rob
i would like to control my bluesound device via javascript. Can you explain to me how to implement "long polling"?
Thank You

**Comment by roblans** [comment]
Hi Andy,

1. A request is sent to the server.
2. The server doesn’t close the connection until it has a message to send.
3. When a message appears – the server responds to the request with it.
4. The client makes a new request immediately.
 
 for more information: https://javascript.info/long-polling

**Comment by andyrichter** [comment]
Hi Rob,
Thank you for your quick response. I think your answer and the given link
for a simple service is very helpful.
Thank you very much !
- Andy -

Am Di., 28. Dez. 2021 um 11:47 Uhr schrieb Rob Lans <
***@***.***>:

**Comment by ScottProkopetz** [comment]
Hi Rob,
I've noticed the PlayerMedia class does not capture all of the response attributes from the Status request. Is there a reason for that or did you only capture the ones that seemed important at the time?

Also, I may be missing something but can't seem to find a way to call GetStatus() to get the entire status response. Is this by design or can you point me in the right direction?

Thanks,
Scott.

**Comment by kjavia** [comment]
@roblans Excellent library. I was trying to replicate the official player in Ionic/React to run on my Android TV. However I ran into a problem. The BluSound player doesn't like a shorter retry interval when the client polls for the status. I had it every 1 second and I started seeing connection errors. I see you have the retry at 5 seconds. Which makes me think that their API is not really useful for a real time player.

**Comment by roblans** [comment]
The retry of 5 seconds is only used to restore the connection  in case of an error. Real time notifications are provided by the long-polling mechanism.

**Comment by kjavia** [comment]
When the player is playing then the web server returns the status and closes the connection. So I have to resend the request for a new status after 1 sec, this is where the problem is. If the player is paused then the long polling connection is kept open.

**Comment by roblans** [comment]
> When the player is playing then the web server returns the status and closes the connection

This is new to me, I'm using this library with 2 different BluOS players and have never encountered this.

**Comment by psiservices-ketan-javia** [comment]
Not sure if this is due to they way `Axios` library in JS works.

**Comment by kjavia** [comment]
I am using React + Axios. Maybe that's the difference? I made some adjustments to prevent unnecessary rendering and now the long polling request just sits there while the player is playing. It only completes when the player pauses or changes tracks (I am using my phone to change the tracks etc.) I am passing the etag and timeout once I get it.
