### ISSUE TITLE
Nuget package with Xamarin VolumeResponse issue

### ISSUE THREAD

**Issue by crwsolutions** [roblans/Blu4Net#4]
When I use the nuget package in my xamarin (.android) project, the following piece of code gives a serialization problem:

```
#if NETSTANDARD2_0
        // workaround for: XmlSerializer works inconsistently with XmlTextAttribute on derived classes
        // https://github.com/dotnet/runtime/issues/22656
        [XmlText()]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string VolumeInternal;
        public int Volume => int.Parse(VolumeInternal);
#else
        [XmlText()]
        public int Volume;
#endif
```

It seems that somehow the 2.1 lib ends up in the build, although the target framework is .Net standard 2.0. When I reference the project via a project reference (source code) everything is fine. Do you have a clue why this is?

**Comment by roblans** [comment]
I've changed to implementation of the LongPollingResponse class (converted it to an interface). So the code is now the same for .Net standard 2.0 and 2.1

New NuGet package published (V 1.0.5)
